### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by dipamsen** [dipamsen/DigiSchool-App#1]

**Comment by Himanshuxyzz** [comment]
what is the issue ?

**Comment by dipamsen** [comment]
@Himanshuxyzz I have already fixed it, just forgot to close the issue! thanks for commenting.

**Comment by Himanshuxyzz** [comment]
so atleast can uhh merge my pr so it can count in hacktober fest plzz can
uhh do this

**Comment by Himanshuxyzz** [comment]
it will be great help for me

**Comment by dipamsen** [comment]
you did not make a pr
